menu:
    Résumé: /
    About: /about/
    Github: https://www.github.com/tiagosantos967

favicon: /favicon.png
logo: /circulartiago.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
ga: UA-90615891-1

# Copyright Infomation
startyear: 2016
